exports.gameArray = [ 
        // "Counter-Strike: Source",
    "Portal",
    "Left 4 Dead 2",
    "Portal 2",
    //"Counter-Strike: Global Offensive",
    //"Vampire: The Masquerade - Bloodlines",
    "Titan Quest",
    "Titan Quest Anniversary Edition",
    // "Titan Quest: Immortal Throne",
    "Quake II",
    // "S.T.A.L.K.E.R.: Shadow of Chernobyl",
    "Far Cry 2",
    // "The Witcher: Enhanced Edition",
    // "Burnout Paradise: The Ultimate Box",
    // "Plants vs. Zombies: Game of the Year",
    "Killing Floor",
    // "Killing Floor Mod: Defence Alliance 2",
    // "The Elder Scrolls IV: Oblivion ",
    "Trine",
    "Osmos",
    "Risen",
    "Torchlight",
    // "Serious Sam HD: The First Encounter",
    // "Serious Sam Fusion 2017 (beta)",
    "Gratuitous Space Battles",
    "BioShock 2",
    "BioShock 2 Remastered",
    "Mass Effect 2",
    // "S.T.A.L.K.E.R.: Call of Pripyat",
    "Metro 2033",
    // "Battlefield: Bad Company 2",
    "Just Cause 2",
    // "Serious Sam HD: The Second Encounter",
    // "SEGA Mega Drive & Genesis Classics",
    // "Fallout: New Vegas",
    "Mafia II",
    "Dota 2 Test",
    "Darksiders",
    "Darksiders Warmastered Edition",
    "Chime",
    // "Recettear: An Item Shop\s Tale",
    "VVVVVV",
    "Monday Night Combat",
    "Magicka",
    "SpaceChem",
    "NightSky",
    "Cogs",
    "Super Meat Boy",
    "Sanctum",
    "RAGE",
    "Terraria",
    "Frozen Synapse",
    // "Red Faction: Armageddon",
    "Jamestown",
    // "Saints Row: The Third",
    // "The Elder Scrolls V: Skyrim",
    "Bastion",
    // "Serious Sam 3: BFE",
    // "PAYDAY: The Heist",
    "Anno 2070",
    // "Cave Story+",
    "Alan Wake",
    // "Superbrothers: Sword & Sworcery EP",
    "The Walking Dead",
    "Torchlight II",
    "Endless Space",
    // "Spec Ops: The Line",
    // "BIT.TRIP RUNNER",
    // "DARK SOULS™: Prepare To Die Edition",
    "Dishonored",
    // "FTL: Faster Than Light",
    "Borderlands 2",
    "Hotline Miami",
    // "Chivalry: Medieval Warfare",
    "BioShock Infinite",
    // "XCOM: Enemy Unknown",
    // "Far Cry® 3",
    "Scribblenauts Unlimited",
    // "Hitman: Absolution",
    // "Hitman: Sniper Challenge",
    "Super Hexagon",
    // "Baldur\s Gate: Enhanced Edition",
    "Antichamber",
    // "Brütal Legend",
    "Warframe",
    "Path of Exile",
    "StarForge",
    "Monaco",
    "Shadowrun Returns",
    "System Shock 2",
    "The Incredible Adventures of Van Helsing",
    // "Dust: An Elysian Tail",
    "The Swapper",
    "Rogue Legacy",
    "Trine 2",
    "Europa Universalis IV",
    "Saints Row IV",
    "Banished",
    "Cook, Serve, Delicious!",
    "Spelunky"];